### ISSUE TITLE
wasm-component-ld --help doesn't work in 0.1.5

### ISSUE THREAD

**Issue by TerrorJack** [alexcrichton/wasm-component-ld#2]
I get `error: invalid option '--help'` in 0.1.5 where it used to work in 0.1.4.

**Comment by alexcrichton** [comment]
Yes this is a consequence of https://github.com/alexcrichton/wasm-component-ld/commit/9786bc767abfe512d20ccc7c96f790d2c20a8200 because linkers generally work with nonstandard command lines so it wasn't possible to use a convenience crate like `clap` to get `--help` auto-generated. It'll need to be handwritten instead.
